### ISSUE TITLE
can not out polar project

### ISSUE THREAD

**Issue by lwk1542** [dawhite/MCTK#24]
Dear Prof.:
    I am a student. I appreciate that the MCTK helped me make many things. However,  a error occurred when I process  a MODIS L1B file, today. I am not able to fix this error. After checking processor, i think the error was trigered by the output polar, projection, which is my needness. Please give me some advices. thanks!!!
### the code:
```
pro test_batch_modis_conversion_level_1b
  compile_opt idl2
  E = ENVI(/HEADLESS)
  modis_l1b_file = 'J:\old_modis\20151222_2\MOD021KM.A2015356.1640.061.2017323113709.hdf'
  ;The specified output location MUST end in the appropriate path
  ;separator for your OS
  output_location = 'J:\old_modis'
  output_rootname = 'level_1b'
  ;Calibration method schema is:
  ;0 = Radiance \ Emissivity, 1 = Reflectance \ Emissivity
  calib_method = 1
  ;Output method schema is:
  ;0 = Standard, 1 = Projected, 2 = Standard and Projected
  out_method = 1
  output_projection = envi_proj_create(/geographic,PE_COORD_SYS_CODE=102021); 102021 is a code of projection stored in EnviPEProjcsStrings.txt 
  ;Use bow tie correction during the projection process
  convert_modis_data, in_file=modis_l1b_file, out_path=output_location, $
    out_root=output_rootname, /l1b, out_method=out_method, $
    out_proj=output_projection, calib_method=calib_method, /bowtie, $
    sd_pos=[0], /no_msg, background=0.0
end
```
the result: (the background image is Landsat 8 OLI data, and error MODIS located upper left)
![微信图片_20191204102303](https://user-images.githubusercontent.com/16815156/70106984-2d4f0600-1680-11ea-966f-5c16b5522104.png)

**Comment by dawhite** [comment]
I think the issue is that you're confusing ENVI. You're telling it that the projection is geographic when it's actually not. I recommend that you use the Universal Polar Stereographic (UPS) definitions as outlined in this document: http://earth-info.nga.mil/GandG/publications/tm8358.2/TM8358_2.pdf. When MCTK users request a UTM projection and a Polar one is more appropriate, UPS is what it switches to automatically. The northern projection covers 83.5 to 90.0 degrees latitude, the southern projection covers -79.5 to -90.0. Here is how you define them in your code:

ups_north = envi_proj_create(PE_COORD_SYS_CODE=32661, type=42, name='UPS_North')
ups_south = envi_proj_create(PE_COORD_SYS_CODE=32761, type=42, name='UPS_South')

If you really want to use 102021, try removing "/geographic" and adding "type=7" instead to the code you have.
