### ISSUE TITLE
APIs for custom data

### ISSUE THREAD

**Issue by jiaozhh** [dawhite/MCTK#8]
Hi dawhite,
Can you give some APIs to support custom georegistration? For example, I can get the geolocated data by your APIs using latitude and longitude bands and my retrieved data band from MODIS L1B and MOD03 data.
Cheers!

**Comment by dawhite** [comment]
If I understand your request, you're wanting to supply your own image data and geolocation data to the projection engine that sits underneath MCTK.  I think a better approach in that situation is to use the IGM/GLT option built into ENVI.  Not the old, slow one available in Classic.  This one: https://www.exelisvis.com/docs/envireprojectglttask.html

**Comment by jiaozhh** [comment]
Ok, thanks. But as I known before, the results between MCTK and IGM/GLT in ENVI were not identical. This is why I request a favour of you. I will test the new API in ENVI. Thank you again.

**Comment by dawhite** [comment]
Exposing the projection engine in the way you suggest would not be a simple process.  It's not impossible to do it, but right now it's not set up for that kind of access, so I'd have to spend a lot of time on the task.  There will definitely be differences between MCTK/VCTK/EPOC output, which all share the same engine, and what comes out of ENVI's new GLT system.

**Comment by jiaozhh** [comment]
Today, I compare the results of geolocating MOD021KM data from MCTK and ENVI's new GLT system "Georeference MODIS". I found that they have a systematic alignment bias. Although I don't know which is more accurate, MCTK looks like a better result. For example, "Georeference MODIS" can only get less geographical range of geolocated data, and gets some flawed pixels.

**Comment by dawhite** [comment]
I'm not surprised by the alignment issue.  Some version of that has existed between MCTK and ENVI since the first version of the plugin.  I recently made some big changes to the projection engine (to be released soon), so perhaps the issue will go away or at least be minimized, but I'm not exactly sure what they are doing in their approach and I haven't done a spatial accuracy study because the spatial resolution is so coarse.  What I have done is spend a lot of time trying to get the projection process right for all possible use cases, which is why it won't be easy to expose the capability through an API.  I do a lot of prep work on the image and geolocation data.

**Comment by jiaozhh** [comment]
Thanks for your reply and hard work on MCTK. I will  test the results of MOD021KM from MCTK and ENVI "Georeference MODIS" tool, and compare them with MRTSwath that is considered as the reference. Looking forward to your new release of MCTK!

**Comment by jiaozhh** [comment]
I tested the results of one MOD021KM data from MCTK, ENVI "Georeference MODIS" tool and MRTSwath. I found that results from ENVI and MRTSwath are more consistent than MCTK and MRTSwath. And then I checked the results with google earth, and found that MCTK has some alignment biases.

**Comment by dawhite** [comment]
Hence why I've been making revisions to the projection engine.  Not that Google Earth is the best way to check for geospatial accuracy, though.  I think treating MRTSwath as the reference implementation makes sense.  I'll run some scenes through that tool and the new version of MCTK and see what happens.

**Comment by dawhite** [comment]
I have some results.  There were two issues that needed to be addressed before MCTK and MRTSwath output for L1B could align with one another.  The first was that for L1B specifically, and I'm still not sure how this happened, MOD03 geolocation files provided through the GUI were not being honored.  They are now.  The second was a small residual spatial mismatch (about a half-pixel in x and y) in the output grid, which the new version of the projection engine resolves.  Remaining differences are the result of resampling algorithm implementation.  Personally, I think the output from MCTK looks more clear.  The bilinear and cubic options in MRTSwath create very blurry images.  My goal is to get the new version of MCTK released within the week.

**Comment by jiaozhh** [comment]
That is a good news! It is noted that when I use geographical projection, geolocated image by MRTSwath can have the same pixel sizes in x and y directions, but different pixel sizes of images from MCTK can be found. And MCTK cannot change this default setting.  Thanks again.

**Comment by dawhite** [comment]
That is by design. "Geographic" is a spherical coordinate system, not Cartesian, so the actual distance covered on the Earth's surface by each pixel in x and y depends on where you are.  Enforcing "square" pixels in that system can actually lead to less accurate gridding results.  For people who truly want to override that aspect of MCTK processing, they can do so through the API.
